export const GET_REGION_INFO = "GET_REGION_INFO";
export const FETCH_REGION_DATA_REQUEST = "FETCH_REGION_DATA_REQUEST";
export const FETCH_REGION_DATA_SUCCESS = "FETCH_REGION_DATA_SUCCESS";
export const FETCH_REGION_DATA_FAILURE = "FETCH_REGION_DATA_FAILURE";
export const FETCH_REGIONINFO_DATA_REQUEST = "FETCH_REGIONINFO_DATA_REQUEST";
export const FETCH_REGIONINFO_DATA_SUCCESS = "FETCH_REGIONINFO_DATA_SUCCESS";
export const FETCH_REGIONINFO_DATA_FAILURE = "FETCH_REGIONINFO_DATA_FAILURE";